ConflictException: Existing customer for externalCustomer 12345 already exists and is not a person
